version: '3.8'
services:
  # MongoDB Service
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  # Backend Service
  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: mongodb://mongo:27017/todolist
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    restart: always

  # Frontend Service 
  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - '3000:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always

volumes:
  mongo-data:
